version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - ./frontend/:/react-docker:delegated
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development

  backend:
    build: ./backend
    ports:
      - 8000:8000
    networks:
      - app-network
    environment:
      - APP_ENV=production

networks:
  app-network:
    driver: bridge