name: Docker Build and Test

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  validate-dockerfiles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate ${{ matrix.service }} Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          check: true
          build-args: |
            BUILDKIT_DOCKERFILE_CHECK=error=true

  build-and-test:
    needs: validate-dockerfiles
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          tags: ${{ matrix.service }}:ci
          target: ${{ matrix.service == 'frontend' && 'tester' || 'default' }}
          load: true

      - name: Run ${{ matrix.service }} tests
        run: |
          if [ "${{ matrix.service }}" = "frontend" ]; then
            docker run --rm frontend:ci npm test
          else
            docker run --rm backend:ci pytest tests/
          fi